Web/Gradebook.Web/Areas/Teacher/Controllers/EvaluationsController.cs
namespace Gradebook.Web.Areas.Teacher.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Castle.Core.Internal;
    using Castle.Core.Logging;
    using Common;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Services.Interfaces;
    using ViewModels.InputModels;
    using Web.ViewModels;
    using Web.ViewModels.InputModels;
    using Web.ViewModels.Subject;

    [Authorize(Roles = GlobalConstants.PrincipalRoleName + "," + GlobalConstants.AdministratorRoleName + "," + GlobalConstants.TeacherRoleName)]
    [Area("Teacher")]
    public class EvaluationsController : Controller
    {
        private readonly ILogger<EvaluationsController> _logger;
        private readonly IAbsencesService _absencesService;
        private readonly IGradesService _gradesService;
        private readonly IStudentsService _studentsService;
        private readonly ISubjectsService _subjectsService;

        public EvaluationsController(ILogger<EvaluationsController> logger, IAbsencesService absencesService, IGradesService gradesService, IStudentsService studentsService, ISubjectsService subjectsService)
        {
            _logger = logger;
            _absencesService = absencesService;
            _gradesService = gradesService;
            _studentsService = studentsService;
            _subjectsService = subjectsService;
        }
    
        //ToDo: Add logic for Create, Edit, Delete Absences AND MARKS
        // ToDo: Add page where teacher can view marks and absences for a single student for a single subject (add validation for which teacher can see/edit which page)

        public IActionResult StudentSubjectDetails(int studentId, int subjectId)
        {
            var viewModel = _subjectsService.GetStudentSubjectPair<StudentSubjectViewModel>(studentId, subjectId);
            if (viewModel == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(viewModel);
        }
        
        public IActionResult AddGrade(int studentId, int subjectId, int teacherId)
        {
            var student = _studentsService.GetById<StudentViewModel>(studentId);
            var inputModel = new GradeCreateInputModel
            {
                Grade = new GradeInputModel
                {
                    TeacherId = teacherId,
                    StudentId = studentId,
                    SubjectId = subjectId,
                },
                StudentName = $"{student.FirstName} {student.LastName}"
            };

            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddGrade(GradeCreateInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await _gradesService.CreateAsync(inputModel.Grade);

                return RedirectToAction("ById", "Subjects", new { area = string.Empty, id = inputModel.Grade.SubjectId });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during new grade record creation. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult EditGrade(int id)
        {
            var grade = _gradesService.GetById<GradeInputModel>(id);
            var inputModel = new GradeModifyInputModel()
            {
                Id = id,
                Grade = grade
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditGrade(GradeModifyInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await _gradesService.EditAsync(inputModel);

                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during student UPDATE operation for grade with id {inputModel.Id}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult DeleteGrade(int id)
        {
            var grade = _gradesService.GetById<GradeInputModel>(id);
            var inputModel = new GradeModifyInputModel()
            {
                Id = id,
                Grade = grade
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteGrade(GradeModifyInputModel inputModel, string onSubmitAction)
        {
            if (onSubmitAction.IsNullOrEmpty() || onSubmitAction == "Cancel")
            {
                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });
            }

            try
            {
                await _gradesService.DeleteAsync(inputModel.Id);

                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during student DELETE operation for grade with id {inputModel.Id}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult AddAbsence(int studentId, int subjectId, int teacherId)
        {
            var student = _studentsService.GetById<StudentViewModel>(studentId);
            var inputModel = new AbsenceCreateInputModel()
            {
                Absence = new AbsenceInputModel
                {
                    TeacherId = teacherId,
                    StudentId = studentId,
                    SubjectId = subjectId,
                },
                StudentName = $"{student.FirstName} {student.LastName}"
            };

            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAbsence(AbsenceCreateInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await _absencesService.CreateAsync(inputModel.Absence);

                return RedirectToAction("ById", "Subjects", new { area = string.Empty, id = inputModel.Absence.SubjectId });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during new absence record creation. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult EditAbsence(int id)
        {
            var absence = _absencesService.GetById<AbsenceInputModel>(id);
            var inputModel = new AbsenceModifyInputModel()
            {
                Id = id,
                Absence = absence
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAbsence(AbsenceModifyInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                await _absencesService.EditAsync(inputModel);

                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during student UPDATE operation for absence with id {inputModel.Id}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult DeleteAbsence(int id)
        {
            var absence = _absencesService.GetById<AbsenceInputModel>(id);
            var inputModel = new AbsenceModifyInputModel()
            {
                Id = id,
                Absence = absence
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAbsence(AbsenceModifyInputModel inputModel, string onSubmitAction)
        {
            if (onSubmitAction.IsNullOrEmpty() || onSubmitAction == "Cancel")
            {
                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });
            }

            try
            {
                await _absencesService.DeleteAsync(inputModel.Id);

                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during student DELETE operation for absence with id {inputModel.Id}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/AddAbsence.cshtml
@using Gradebook.Data.Models.Grades
@using Gradebook.Data.Models.Absences
@model Gradebook.Web.Areas.Teacher.ViewModels.InputModels.AbsenceCreateInputModel
@{
    ViewData["Title"] = "Add Absence";
}

<h3 class="page-heading">Add new absence for @Model.StudentName</h3>
<form asp-action="AddAbsence" method="post">
    <div>
        <label asp-for="Absence.Period"></label>
        <select asp-for="Absence.Period" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<GradePeriod>()">
            <option>Select period: </option>
        </select>
        <span asp-validation-for="Absence.Period" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Absence.Type"></label>
        <select asp-for="Absence.Type" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<AbsenceType>()">
            <option>Select absence type: </option>
        </select>
        <span asp-validation-for="Absence.Type" class="text-danger"></span>
    </div>

    <div>
        <input type="hidden" asp-for="Absence.TeacherId"/>
        <input type="hidden" asp-for="Absence.StudentId"/>
        <input type="hidden" asp-for="Absence.SubjectId"/>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Add absence"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/AddGrade.cshtml
@using Gradebook.Data.Models.Grades
@model Gradebook.Web.Areas.Teacher.ViewModels.InputModels.GradeCreateInputModel
@{
    ViewData["Title"] = "Add Grade";
}

<h3 class="page-heading">Add new grade for @Model.StudentName</h3>
<form asp-action="AddGrade" method="post">
    <div>
        <label asp-for="Grade.Value">Grade: </label>
        <input asp-for="Grade.Value" class="form-control" aria-describedby="gradeDesc"/>
        <span asp-validation-for="Grade.Value" class="text-danger"></span>
        <small id="gradeDesc" class="form-text text-muted">
            Note: Grade should be in the range between 2.00 and 6.00
        </small>
    </div>
    
    <div>
        <label asp-for="Grade.Period"></label>
        <select asp-for="Grade.Period" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<GradePeriod>()">
            <option>Select period: </option>
        </select>
        <span asp-validation-for="Grade.Period" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Grade.Type"></label>
        <select asp-for="Grade.Type" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<GradeType>()">
            <option>Select grade type: </option>
        </select>
        <span asp-validation-for="Grade.Type" class="text-danger"></span>
    </div>

    <div>
        <input type="hidden" asp-for="Grade.TeacherId"/>
        <input type="hidden" asp-for="Grade.StudentId"/>
        <input type="hidden" asp-for="Grade.SubjectId"/>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Add grade"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/DeleteAbsence.cshtml
@model Gradebook.Web.Areas.Teacher.ViewModels.InputModels.AbsenceModifyInputModel
@{
    ViewData["Title"] = "Delete Absence";
}

<h3 class="page-heading">Delete absence</h3>
<form asp-action="DeleteAbsence" method="post">
    <div>
        <label asp-for="Absence.Period"></label>
        <input asp-for="Absence.Period" class="form-control" readonly/>
        <span asp-validation-for="Absence.Period" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Absence.Type"></label>
        <input asp-for="Absence.Type" class="form-control" readonly/>
        <span asp-validation-for="Absence.Type" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" name="onSubmitAction" class="btn btn-light" value="Cancel"/>
        <input type="submit" name="onSubmitAction" class="btn btn-primary delete-record-btn" value="Delete Absence" onclick="return confirm(`Are you sure you want to delete that absence?`)"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/DeleteGrade.cshtml
@model Gradebook.Web.Areas.Teacher.ViewModels.InputModels.GradeModifyInputModel
@{
    ViewData["Title"] = "Delete Grade";
}

<h3 class="page-heading">Delete grade</h3>
<form asp-action="DeleteGrade" method="post">
    <div>
        <label asp-for="Grade.Value">Grade: </label>
        <input asp-for="Grade.Value" class="form-control"/>
        <span asp-validation-for="Grade.Value" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Grade.Period"></label>
        <input asp-for="Grade.Period" class="form-control" readonly/>
        <span asp-validation-for="Grade.Period" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Grade.Type"></label>
        <input asp-for="Grade.Type" class="form-control" readonly/>
        <span asp-validation-for="Grade.Type" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" name="onSubmitAction" class="btn btn-light" value="Cancel"/>
        <input type="submit" name="onSubmitAction" class="btn btn-primary delete-record-btn" value="Delete Grade" onclick="return confirm(`Are you sure you want to delete that grade?`)"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/EditAbsence.cshtml
@using Gradebook.Data.Models.Grades
@using Gradebook.Data.Models.Absences
@model Gradebook.Web.Areas.Teacher.ViewModels.InputModels.AbsenceModifyInputModel
@{
    ViewData["Title"] = "Edit Absence";
}

<h3 class="page-heading">Edit absence</h3>
<form asp-action="EditAbsence" method="post">
    <div>
        <label asp-for="Absence.Period"></label>
        <select asp-for="Absence.Period" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<GradePeriod>()">
            <option>Select period: </option>
        </select>
        <span asp-validation-for="Absence.Period" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Absence.Type"></label>
        <select asp-for="Absence.Type" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<AbsenceType>()">
            <option>Select absence type: </option>
        </select>
        <span asp-validation-for="Absence.Type" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Edit absence"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/EditGrade.cshtml
@using Gradebook.Data.Models.Grades
@model Gradebook.Web.Areas.Teacher.ViewModels.InputModels.GradeModifyInputModel
@{
    ViewData["Title"] = "Edit Grade";
}

<h3 class="page-heading">Edit grade</h3>
<form asp-action="EditGrade" method="post">
    <div>
        <label asp-for="Grade.Value">Grade: </label>
        <input asp-for="Grade.Value" class="form-control" aria-describedby="gradeDesc"/>
        <span asp-validation-for="Grade.Value" class="text-danger"></span>
        <small id="gradeDesc" class="form-text text-muted">
            Note: Grade should be in the range between 2.00 and 6.00
        </small>
    </div>
    
    <div>
        <label asp-for="Grade.Period"></label>
        <select asp-for="Grade.Period" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<GradePeriod>()">
            <option>Select period: </option>
        </select>
        <span asp-validation-for="Grade.Period" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Grade.Type"></label>
        <select asp-for="Grade.Type" 
                class="form-control" 
                asp-items="Html.GetEnumSelectList<GradeType>()">
            <option>Select grade type: </option>
        </select>
        <span asp-validation-for="Grade.Type" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Edit grade"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Teacher/Views/Evaluations/StudentSubjectDetails.cshtml
@using Gradebook.Data.Models.Grades
@using Gradebook.Data.Models.Absences
@model Gradebook.Web.ViewModels.Subject.StudentSubjectViewModel
@{
    ViewData["Title"] = "Student details for subject";

    string GetNumericAbsenceByType(AbsenceType type)
    {
        if (type == AbsenceType.OneThird)
        {
            return "1/3";
        }
        return "1";
    }
}

<h3 class="page-heading">Grades and absences of @Model.StudentFullName in @Model.SubjectName</h3>

<div>
    <h5>
        Grades:
    </h5>
    <p>
        @if (Model.GradesByPeriod.ContainsKey(GradePeriod.FirstTerm))
        {
            <span><b>First term grades:</b> </span>
            @foreach (var grade in Model.GradesByPeriod[GradePeriod.FirstTerm].Where(g => g.Type == GradeType.Normal))
            {
                <span>@grade.Value  
                    <a class="page-link-green" asp-controller="Evaluations" asp-action="EditGrade" asp-route-id="@grade.Id" title="Edit grade">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a class="page-link-red" asp-controller="Evaluations" asp-action="DeleteGrade" asp-route-id="@grade.Id" title="Delete grade">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                  | 
                </span>
            }
            if (Model.GradesByPeriod[GradePeriod.FirstTerm].Any(g => g.Type == GradeType.Final))
            {
                <br>
                <span>Final grade(s): </span>
                @foreach (var grade in Model.GradesByPeriod[GradePeriod.FirstTerm].Where(g => g.Type == GradeType.Final))
                {
                    <span>@grade.Value  
                        <a class="page-link-green" asp-controller="Evaluations" asp-action="EditGrade" asp-route-id="@grade.Id" title="Edit grade">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                        <a class="page-link-red" asp-controller="Evaluations" asp-action="DeleteGrade" asp-route-id="@grade.Id" title="Delete grade">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                        | 
                    </span>
                }
            }
            <br>
        }
        @if (Model.GradesByPeriod.ContainsKey(GradePeriod.SecondTerm))
        {
            <span><b>Second term grades:</b> </span>
            @foreach (var grade in Model.GradesByPeriod[GradePeriod.SecondTerm].Where(g => g.Type == GradeType.Normal))
            {
                <span>@grade.Value  
                    <a class="page-link-green" asp-controller="Evaluations" asp-action="EditGrade" asp-route-id="@grade.Id" title="Edit grade">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a class="page-link-red" asp-controller="Evaluations" asp-action="DeleteGrade" asp-route-id="@grade.Id" title="Delete grade">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                    | 
                </span>
            }
            if (Model.GradesByPeriod[GradePeriod.SecondTerm].Any(g => g.Type == GradeType.Final))
            {
                <br>
                <span>Final grade(s): </span>
                @foreach (var grade in Model.GradesByPeriod[GradePeriod.SecondTerm].Where(g => g.Type == GradeType.Final))
                {
                    <span>@grade.Value  
                        <a class="page-link-green" asp-controller="Evaluations" asp-action="EditGrade" asp-route-id="@grade.Id" title="Edit grade">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </a>
                        <a class="page-link-red" asp-controller="Evaluations" asp-action="DeleteGrade" asp-route-id="@grade.Id" title="Delete grade">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                        </a>
                        | 
                    </span>
                }
            }
        }
    </p>
</div>
<div>
    <h5>
        Absences:
    </h5>
    <p>
        @if (Model.Absences.Any(a => a.Period == AbsencePeriod.FirstTerm))
        {
            <span><b>First term absences (historically):</b> </span>
            @foreach (var absence in Model.Absences.Where(a => a.Period == AbsencePeriod.FirstTerm))
            {
                <span>@GetNumericAbsenceByType(@absence.Type) 
                    <a class="page-link-green" asp-controller="Evaluations" asp-action="EditAbsence" asp-route-id="@absence.Id" title="Edit absence">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a class="page-link-red" asp-controller="Evaluations" asp-action="DeleteAbsence" asp-route-id="@absence.Id" title="Delete absence">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                    | 
                </span>
            }
            <br>
        }
        @if (Model.Absences.Any(a => a.Period == AbsencePeriod.SecondTerm))
        {
            <span><b>First term absences (historically):</b> </span>
            @foreach (var absence in Model.Absences.Where(a => a.Period == AbsencePeriod.SecondTerm))
            {
                <span>@GetNumericAbsenceByType(@absence.Type) 
                    <a class="page-link-green" asp-controller="Evaluations" asp-action="EditAbsence" asp-route-id="@absence.Id" title="Edit absence">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>
                    <a class="page-link-red" asp-controller="Evaluations" asp-action="DeleteAbsence" asp-route-id="@absence.Id" title="Delete absence">
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                    | 
                </span>
            }
        }
    </p>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}