Web/Gradebook.Web/Areas/Principal/Controllers/ManagementController.cs
namespace Gradebook.Web.Areas.Principal
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Xml.Schema;
    using Castle.Core.Internal;
    using Castle.Core.Logging;
    using Common;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.Extensions.Logging;
    using Services.Interfaces;
    using ViewModels.InputModels;
    using Web.ViewModels;
    using Web.ViewModels.Administration;
    using Web.ViewModels.Classes;
    using Web.ViewModels.Home;
    using Web.ViewModels.InputModels;
    using Web.ViewModels.Principal;
    using Web.ViewModels.Subject;

    [Authorize(Roles = GlobalConstants.PrincipalRoleName + "," + GlobalConstants.AdministratorRoleName)]
    [Area("Principal")]
    public class ManagementController : Controller
    {
        private readonly ILogger<ManagementController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISchoolsServices _schoolsServices;
        private readonly IStudentsService _studentsService;
        private readonly ITeachersService _teachersService;
        private readonly ISubjectsService _subjectsService;
        private readonly IParentsService _parentsService;
        private readonly IClassesService _classesService;

        public ManagementController(
            ILogger<ManagementController> logger,
            UserManager<ApplicationUser> userManager,
            ISchoolsServices schoolsServices,
            IStudentsService studentsService,
            ITeachersService teachersService,
            ISubjectsService subjectsService,
            IParentsService parentsService,
            IClassesService classesService)
        {
            _logger = logger;
            _userManager = userManager;
            _schoolsServices = schoolsServices;
            _studentsService = studentsService;
            _teachersService = teachersService;
            _subjectsService = subjectsService;
            _parentsService = parentsService;
            _classesService = classesService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddClassToSubject()
        {
            var user = await _userManager.GetUserAsync(User);
            var isAdmin = await IsAdmin();
            var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user?.UniqueGradebookId, isAdmin).Select(s => s.Id);
            var classesInSchool = _classesService.GetAllByMultipleSchoolIds<ClassViewModel>(schoolIds.ToList());
            var subjectsInSchool = _subjectsService.GetAllByMultipleSchoolIds<SubjectViewModel>(schoolIds.ToList());
            var inputModel = new ClassSubjectCreateInputModel
            {
                Classes = classesInSchool.Select(c => new SelectListItem($"{c.Year}{c.Letter} ({c.Teacher.SchoolName})", c.Id.ToString())).ToList(),
                Subjects = subjectsInSchool.Select(s => new SelectListItem($"{s.Name} ({s.TeacherSchoolName})({s.TeacherFullName})", s.Id.ToString())).ToList(),
            };
            return View(inputModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddClassToSubject(ClassSubjectCreateInputModel inputModel)
        {
            if (!ModelState.IsValid || inputModel.ClassSubjectPair.ClassId.IsNullOrEmpty() || inputModel.ClassSubjectPair.SubjectId.IsNullOrEmpty())
            {
                return View(inputModel);
            }

            try
            {
                await _subjectsService.AssignAllStudentsFromClassToSubject(inputModel.ClassSubjectPair);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during map between class with ID {inputModel.ClassSubjectPair.ClassId} and subject with ID {inputModel.ClassSubjectPair.SubjectId}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> CreateSubject()
        {
            var user = await _userManager.GetUserAsync(User);
            var isAdmin = await IsAdmin();
            var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user?.UniqueGradebookId, isAdmin).Select(s => s.Id);
            var teachersInSchools = _teachersService.GetAllBySchoolIds<TeacherViewModel>(schoolIds);
            var inputModel = new SubjectCreateInputModel
            {
                Teachers = teachersInSchools.Select(t => new SelectListItem($"{t.FirstName} {t.LastName} ({t.SchoolName})", t.Id.ToString())).ToList()
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSubject(SubjectCreateInputModel inputModel)
        {
            if (!ModelState.IsValid || inputModel.Subject.TeacherId.IsNullOrEmpty())
            {
                //ToDo: in case of null teacher, return appropriate message or add model validation?
                return View(inputModel);
            }

            try
            {
               await _subjectsService.CreateSubject(inputModel.Subject);

               return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during new subject record creation. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> EditSubject(int id)
        {
            var user = await _userManager.GetUserAsync(User);
            var isAdmin = await IsAdmin();
            var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user?.UniqueGradebookId, isAdmin).Select(s => s.Id);
            var teachersInSchools = _teachersService.GetAllBySchoolIds<TeacherViewModel>(schoolIds);
            var subject = _subjectsService.GetById<SubjectInputModel>(id);
            var inputModel = new SubjectModifyInputModel()
            {
                Id = id,
                Teachers = teachersInSchools.Select(t => new SelectListItem($"{t.FirstName} {t.LastName} ({t.SchoolName})", t.Id.ToString())).ToList(),
                Subject = subject
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSubject(SubjectModifyInputModel inputModel)
        {
            if (!ModelState.IsValid || inputModel.Subject.TeacherId.IsNullOrEmpty())
            {
                //ToDo: in case of null teacher, return appropriate message or add model validation?
                return View(inputModel);
            }

            try
            {
                await _subjectsService.EditAsync(inputModel);

                return RedirectToAction("ById", "Subjects", new { area = string.Empty, id = inputModel.Id });
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during student UPDATE operation for subject with id {inputModel.Id}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult DeleteSubject(int id)
        {
            var subject = _subjectsService.GetById<SubjectInputModel>(id);
            var inputModel = new SubjectModifyInputModel()
            {
                Id = id,
                Subject = subject
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteSubject(SubjectModifyInputModel inputModel, string onSubmitAction)
        {
            if (onSubmitAction.IsNullOrEmpty() || onSubmitAction == "Cancel")
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                await _subjectsService.DeleteAsync(inputModel.Id);

                return RedirectToAction("SubjectsList", "Subjects", new { area = string.Empty });  // string is empty in order to exit current principal area
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"An exception occured during student DELETE operation for subject with id {inputModel.Id}. Ex: {e.Message}");
                return RedirectToAction("Error", "Home");
            }
        }

        public async Task<IActionResult> CreateClass()
        {
            var user = await _userManager.GetUserAsync(User);
            var isAdmin = await IsAdmin();
            var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user?.UniqueGradebookId, isAdmin).Select(s => s.Id);
            var teachersInSchools = _teachersService.GetAllBySchoolIds<TeacherViewModel>(schoolIds);
            var inputModel = new ClassCreateInputModel
            {
                Teachers = teachersInSchools.Select(t => new SelectListItem($"{t.FirstName} {t.LastName} ({t.SchoolName})", t.Id.ToString())).ToList()
            };
            return View(inputModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateClass(ClassCreateInputModel inputModel)
        {
            if (!ModelState.IsValid || inputModel.Class.TeacherId.IsNullOrEmpty())
            {
                //ToDo: in case of null teacher, return appropriate message or add model validation?
                return View(inputModel);
            }

            try
            {
                await _classesService.CreateAsync(inputModel.Class);

                return RedirectToAction(nameof(Index));
            }

Web/Gradebook.Web/Controllers/ClassesController.cs
namespace Gradebook.Web.Areas.Principal
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Common;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using Web.ViewModels.Classes;
    using Web.ViewModels.Home;
    using Web.ViewModels.Principal;
    using Web.ViewModels.Subject;

    public class ClassesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IClassesService _classesService;
        private readonly ISchoolsServices _schoolsServices;
        private readonly ITeachersService _teachersService;
        private readonly IStudentsService _studentsService;
        private readonly IParentsService _parentsService;

        public ClassesController(
            UserManager<ApplicationUser> userManager,
            IClassesService classesService,
            ISchoolsServices schoolsServices,
            ITeachersService teachersService,
            IStudentsService studentsService,
            IParentsService parentsService)
        {
            _userManager = userManager;
            _classesService = classesService;
            _schoolsServices = schoolsServices;
            _teachersService = teachersService;
            _studentsService = studentsService;
            _parentsService = parentsService;
        }
        
        [Authorize]
        public async Task<IActionResult> ClassesList()
        {
            var viewModel = new ClassesListViewModel();
            var classes = await GetClassesBasedOnUserRoleAsync();
            if (classes == null)
            {
                return RedirectToAction("Error", "Home");
            }

            viewModel.Classes = classes;

            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ById(int id)
        {
            var viewModel = _classesService.GetById<ClassViewModel>(id);
            if (!await IsUserAuthorizedToViewPage(viewModel))
            {
                return RedirectToAction("UnauthorizedAttempt", "Home");
            }
            
            return View(viewModel);
        }
        
        private async Task<IEnumerable<ClassViewModel>> GetClassesBasedOnUserRoleAsync()
        {
            if (User.IsInRole(GlobalConstants.TeacherRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var teacherId = _teachersService.GetIdByUniqueId(user.UniqueGradebookId);
                if (teacherId == null)
                {
                    return null; // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllByTeacherId<ClassViewModel>(teacherId.Value);
            }

            if (User.IsInRole(GlobalConstants.StudentRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var studentId = _studentsService.GetIdByUniqueId(user.UniqueGradebookId);
                if (studentId == null)
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllByStudentId<ClassViewModel>(studentId.Value);
            }

            if (User.IsInRole(GlobalConstants.ParentRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var studentIds = _parentsService.GetStudentIdsByParentUniqueId(user.UniqueGradebookId);
                if (!studentIds.Any())
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllByMultipleStudentIds<ClassViewModel>(studentIds);
            }

            if (User.IsInRole(GlobalConstants.PrincipalRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user.UniqueGradebookId).Select(s => s.Id);
                if (!schoolIds.Any())
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllBySchoolId<ClassViewModel>(schoolIds.FirstOrDefault());
            }

            return _classesService.GetAll<ClassViewModel>();
        }

        private async Task<bool> IsUserAuthorizedToViewPage(ClassViewModel viewModel)
        {
            if (User.IsInRole(GlobalConstants.AdministratorRoleName) ||
                User.IsInRole(GlobalConstants.PrincipalRoleName) ||
                User.IsInRole(GlobalConstants.TeacherRoleName))
            {
                return true;
            }
            
            var user = await _userManager.GetUserAsync(User);
            var userUniqueId = user.UniqueGradebookId;

            return viewModel.Teacher.UniqueId == userUniqueId ||
                   viewModel.Students.Any(s => s.UniqueId == userUniqueId) ||
                   viewModel.Students.Any(s => s.StudentParents.Any(sp => sp.Parent.UniqueId == userUniqueId));
        }
    }
}

Web/Gradebook.Web/Views/Classes/ById.cshtml
@using Microsoft.AspNetCore.Identity
@using Gradebook.Data.Models
@using Gradebook.Common
@using Gradebook.Data.Models.Grades
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model Gradebook.Web.ViewModels.Principal.ClassViewModel
@{
    ViewData["Title"] = "Class Details";
    var studentsCounter = 1;

    bool IsCurrentUserPrincipalOrAdmin()
    {
        var user = UserManager.GetUserAsync(User).GetAwaiter().GetResult();
        var roles = UserManager.GetRolesAsync(user).GetAwaiter().GetResult();
        return roles.Any(r => r == GlobalConstants.AdministratorRoleName || r == GlobalConstants.PrincipalRoleName);
    }

    var listCounter = 0;
    var contentCounter = 0;
}

<h3 class="center-custom">
    Class members for @Model.Year@Model.Letter in @Model.Teacher.SchoolName
    @if (IsCurrentUserPrincipalOrAdmin())
    {
        <a class="page-link-green" asp-area="Principal" asp-controller="Management" asp-action="EditClass" asp-route-id="@Model.Id" title="Edit class">
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        </a>
        <a class="page-link-red" asp-area="Principal" asp-controller="Management" asp-action="DeleteClass" asp-route-id="@Model.Id" title="Delete class">
            <i class="fa fa-trash-o" aria-hidden="true"></i>
        </a>
    }
    <a class="page-link-red" asp-action="ClassesList" asp-route-id="@Model.Id" title="Go to classes list">
        <i class="fa fa-list" aria-hidden="true"></i>
    </a>
</h3>
<h5 class="page-heading">Below you can see the details about each studen in @Model.Year@Model.Letter class </h5>
<hr>

<div class="row">
    <div class="col-4">
        <div class="list-group" id="list-tab" role="tablist">
            @foreach (var student in Model.Students)
            {
                @if (listCounter++ == 0)
                {
                    <a class="list-group-item list-group-item-action active" id="list-@student.Id-list" data-toggle="list" href="#list-@student.Id" role="tab" aria-controls="@student.Id">@student.FirstName @student.LastName</a>
                }
                else
                {
                    <a class="list-group-item list-group-item-action" id="list-@student.Id-list" data-toggle="list" href="#list-@student.Id" role="tab" aria-controls="@student.Id">@student.FirstName @student.LastName</a>
                }
            }
        </div>
    </div>
    <div class="col-8">
        <div class="tab-content" id="nav-tabContent">
            @foreach (var student in Model.Students)
            {
                if (contentCounter++ == 0)
                {
                    <div class="tab-pane fade show active" id="list-@student.Id" role="tabpanel" aria-labelledby="list-@student.Id-list">
                        <p><b>Email:</b> <span>@student.Email</span></p> 
                        <p><b>Birthday:</b> <span>@student.BirthDate.ToString("dddd, dd MMMM yyyy")</span></p> 
                        @if (IsCurrentUserPrincipalOrAdmin())
                        {
                            <p><b>Modify student</b>: 
                                <a class="page-link-green" asp-area="Principal" asp-controller="Management" asp-action="EditStudent" asp-route-id="@student.Id" title="Edit student">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                <a class="page-link-red" asp-area="Principal" asp-controller="Management" asp-action="DeleteStudent" asp-route-id="@student.Id" title="Delete student">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </p>
                        }
                        <div>
                            <b>Parents:</b>
                            @foreach (var parent in student.StudentParents)
                            {
                                <p>
                                    <i>@parent.Parent.FirstName @parent.Parent.LastName - </i>
                                    <i class="fa fa-envelope" aria-hidden="true"></i> @parent.Parent.Email |
                                    <i class="fa fa-phone" aria-hidden="true"></i> @parent.Parent.PhoneNumber
                                    @if (IsCurrentUserPrincipalOrAdmin())
                                    {
                                        <a class="page-link-green" asp-area="Principal" asp-controller="Management" asp-action="EditParent" asp-route-id="@parent.Parent.Id" title="Edit parent">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                        <a class="page-link-red" asp-area="Principal" asp-controller="Management" asp-action="DeleteParent" asp-route-id="@parent.Parent.Id" title="Delete parent">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>
                                    }
                                </p>
                            }
                        </div>
                    </div>
                }
                else
                {
                    <div class="tab-pane fade" id="list-@student.Id" role="tabpanel" aria-labelledby="list-@student.Id-list">
                        <p><b>Email:</b> <span>@student.Email</span></p> 
                        <p><b>Birthday:</b> <span>@student.BirthDate.ToString("dddd, dd MMMM yyyy")</span></p> 
                        @if (IsCurrentUserPrincipalOrAdmin())
                        {
                            <p><b>Modify student</b>: 
                                <a class="page-link-green" asp-area="Principal" asp-controller="Management" asp-action="EditStudent" asp-route-id="@student.Id" title="Edit student">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                <a class="page-link-red" asp-area="Principal" asp-controller="Management" asp-action="DeleteStudent" asp-route-id="@student.Id" title="Delete student">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </a>
                            </p>
                        }
                        <div>
                            <b>Parents:</b>
                            @foreach (var parent in student.StudentParents)
                            {
                                <p>
                                    <i>@parent.Parent.FirstName @parent.Parent.LastName -</i>
                                    <i class="fa fa-envelope" aria-hidden="true"></i> @parent.Parent.Email |
                                    <i class="fa fa-phone" aria-hidden="true"></i> @parent.Parent.PhoneNumber
                                    @if (IsCurrentUserPrincipalOrAdmin())
                                    {
                                        <a class="page-link-green" asp-area="Principal" asp-controller="Management" asp-action="EditParent" asp-route-id="@parent.Parent.Id" title="Edit parent">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                        <a class="page-link-red" asp-area="Principal" asp-controller="Management" asp-action="DeleteParent" asp-route-id="@parent.Parent.Id" title="Delete parent">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>
                                    }
                                </p>
                            }
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $('#myList a').on('click', function (e) {
                e.preventDefault()
                $(this).tab('show')
            })
    </script>
}

Web/Gradebook.Web/Views/Classes/ClassesList.cshtml
@using Microsoft.AspNetCore.Identity
@using Gradebook.Data.Models
@using Gradebook.Common
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model Gradebook.Web.ViewModels.Classes.ClassesListViewModel
@{
    ViewData["Title"] = "Class List";

    bool IsCurrentUserPrincipalOrAdmin()
    {
        var user = UserManager.GetUserAsync(User).GetAwaiter().GetResult();
        var roles = UserManager.GetRolesAsync(user).GetAwaiter().GetResult();
        return roles.Any(r => r == GlobalConstants.AdministratorRoleName || r == GlobalConstants.PrincipalRoleName);
    }
}

@foreach (var classesBySchool in @Model.ClassesBySchool)
{
    <h1 class="center-custom">Your visible classes in @classesBySchool.Key</h1>
    @foreach (var schoolClass in classesBySchool.Value.OrderBy(c => c.Year).ThenBy(c => c.Letter))
    {
        <p><b>Letter:</b> @schoolClass.Letter</p>
        <p><b>Year:</b> @schoolClass.Year</p>
        <p><b>Year Create:</b> @schoolClass.YearCreated</p>
        <p><b>Students Count:</b> @schoolClass.Students.Count</p>
        <p><b>Teacher:</b> @schoolClass.TeacherFullName</p>
        <p><b>Average first term grade:</b> @{ var avgGradeFirstTerm = @schoolClass.AverageGradeFirstTerm?.ToString() ?? "n/a";} @avgGradeFirstTerm</p>
        <p><b>Average second term grade:</b> @{ var avgGradeSecondTerm = @schoolClass.AverageGradeSecondTerm?.ToString() ?? "n/a";} @avgGradeSecondTerm</p>

        <button type="button" class="btn btn-outline-success">
            <a class="page-link-with-hover" asp-action="ById" asp-route-id="@schoolClass.Id" title="Class details">
                Details
            </a>
        </button>
        if (IsCurrentUserPrincipalOrAdmin())
        {
            <a class="page-link-green" asp-area="Principal" asp-controller="Management" asp-action="EditClass" asp-route-id="@schoolClass.Id" title="Edit class">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            </a>
            <a class="page-link-red" asp-area="Principal" asp-controller="Management" asp-action="DeleteClass" asp-route-id="@schoolClass.Id" title="Delete class">
                <i class="fa fa-trash-o" aria-hidden="true"></i>
            </a>
        }
        <hr/>
    }
}