Web/Gradebook.Web/Controllers/SettingsController.cs
namespace Gradebook.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Data.Common.Repositories;
    using Data.Models;
    using Gradebook.Services.Data.Interfaces;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.Settings;

    public class SettingsController : BaseController
    {
        private readonly ISettingsService settingsService;

        private readonly IDeletableEntityRepository<Setting> repository;

        public SettingsController(ISettingsService settingsService, IDeletableEntityRepository<Setting> repository)
        {
            this.settingsService = settingsService;
            this.repository = repository;
        }

        public IActionResult Index()
        {
            var settings = settingsService.GetAll<SettingViewModel>();
            var model = new SettingsListViewModel { Settings = settings };
            return View(model);
        }

        public async Task<IActionResult> InsertSetting()
        {
            var random = new Random();
            var setting = new Setting { Name = $"Name_{random.Next()}", Value = $"Value_{random.Next()}" };

            await repository.AddAsync(setting);
            await repository.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Gradebook.Web/Views/Shared/ConfirmCreated.cshtml
@using Gradebook.Common
@model Gradebook.Web.ViewModels.Administration.ConfirmCreatedViewModel
@{
    ViewData["Title"] = "Add school";
}

<h1>New @Model.UserType.ToString() has been created</h1>
<h3>UniqueID: @Model.UniqueId</h3>
<p>Please provide this unique to the person, so that he can register in the @GlobalConstants.SystemName</p>

Web/Gradebook.Web/Views/Shared/PageNotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
}

<div class="center-custom">
    <img src="~images/errors/404.png" class="error-code-image">
    <br>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index" role="button">Go to Home Page</a>
</div>

Web/Gradebook.Web/Views/Shared/UnauthorizedAttempt.cshtml
@{
    ViewData["Title"] = "Unauthorized";
}

<div class="center-custom">
    <img src="~/images/errors/401.jpg" class="error-code-image">
    <br>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index" role="button">Go to Home Page</a>
</div>

Web/Gradebook.Web/Views/Shared/_Layout.cshtml
@using Gradebook.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js" referrerpolicy="origin"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Gradebook.Web/Views/Shared/_Schools.cshtml
<style>
</style>
<script type="text/javascript">
    Vue.component('schools', {
        props: {
            schoolsInput: Array
        },
        data() {
            return {
                currentSchoolIndex: 0,
                schoolsLength: this.schoolsInput.length
            }
        },
        methods: {
            getImageUrl: function () {
                return "images/schools/" + schoolsInput[currentSchoolIndex].SchoolImageName
            }
        },
        template: '#schools-template'
    });
</script>
<script type="text/template" id="schools-template">
    <div>
          <button type="button" class="btn btn-outline-secondary" v-if="currentSchoolIndex > 0" onclick="currentSchoolIndex += 1">
              Previous
          </button>
          <button type="button" class="btn btn-outline-secondary" v-if="currentSchoolIndex < (schoolsLength - 1)" onclick="currentSchoolIndex -=1 ">
              Next
          </button>

        <h1>{{schoolsInput[currentSchoolIndex].Name}} </h1>
        <img :src="getImageUrl()">
        <h3>{{schoolsInput[currentSchoolIndex].Address}}</h3>
    </div>
</script>