Web/Gradebook.Web/Controllers/ClassesController.cs
namespace Gradebook.Web.Areas.Principal
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Common;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using Web.ViewModels.Classes;
    using Web.ViewModels.Home;
    using Web.ViewModels.Principal;
    using Web.ViewModels.Subject;

    public class ClassesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IClassesService _classesService;
        private readonly ISchoolsServices _schoolsServices;
        private readonly ITeachersService _teachersService;
        private readonly IStudentsService _studentsService;
        private readonly IParentsService _parentsService;

        public ClassesController(
            UserManager<ApplicationUser> userManager,
            IClassesService classesService,
            ISchoolsServices schoolsServices,
            ITeachersService teachersService,
            IStudentsService studentsService,
            IParentsService parentsService)
        {
            _userManager = userManager;
            _classesService = classesService;
            _schoolsServices = schoolsServices;
            _teachersService = teachersService;
            _studentsService = studentsService;
            _parentsService = parentsService;
        }
        
        [Authorize]
        public async Task<IActionResult> ClassesList()
        {
            var viewModel = new ClassesListViewModel();
            var classes = await GetClassesBasedOnUserRoleAsync();
            if (classes == null)
            {
                return RedirectToAction("Error", "Home");
            }

            viewModel.Classes = classes;

            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ById(int id)
        {
            var viewModel = _classesService.GetById<ClassViewModel>(id);
            if (!await IsUserAuthorizedToViewPage(viewModel))
            {
                return RedirectToAction("UnauthorizedAttempt", "Home");
            }
            
            return View(viewModel);
        }
        
        private async Task<IEnumerable<ClassViewModel>> GetClassesBasedOnUserRoleAsync()
        {
            if (User.IsInRole(GlobalConstants.TeacherRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var teacherId = _teachersService.GetIdByUniqueId(user.UniqueGradebookId);
                if (teacherId == null)
                {
                    return null; // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllByTeacherId<ClassViewModel>(teacherId.Value);
            }

            if (User.IsInRole(GlobalConstants.StudentRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var studentId = _studentsService.GetIdByUniqueId(user.UniqueGradebookId);
                if (studentId == null)
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllByStudentId<ClassViewModel>(studentId.Value);
            }

            if (User.IsInRole(GlobalConstants.ParentRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var studentIds = _parentsService.GetStudentIdsByParentUniqueId(user.UniqueGradebookId);
                if (!studentIds.Any())
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllByMultipleStudentIds<ClassViewModel>(studentIds);
            }

            if (User.IsInRole(GlobalConstants.PrincipalRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user.UniqueGradebookId).Select(s => s.Id);
                if (!schoolIds.Any())
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _classesService.GetAllBySchoolId<ClassViewModel>(schoolIds.FirstOrDefault());
            }

            return _classesService.GetAll<ClassViewModel>();
        }

        private async Task<bool> IsUserAuthorizedToViewPage(ClassViewModel viewModel)
        {
            if (User.IsInRole(GlobalConstants.AdministratorRoleName) ||
                User.IsInRole(GlobalConstants.PrincipalRoleName) ||
                User.IsInRole(GlobalConstants.TeacherRoleName))
            {
                return true;
            }
            
            var user = await _userManager.GetUserAsync(User);
            var userUniqueId = user.UniqueGradebookId;

            return viewModel.Teacher.UniqueId == userUniqueId ||
                   viewModel.Students.Any(s => s.UniqueId == userUniqueId) ||
                   viewModel.Students.Any(s => s.StudentParents.Any(sp => sp.Parent.UniqueId == userUniqueId));
        }
    }
}

Web/Gradebook.Web/Controllers/SubjectsController.cs
namespace Gradebook.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Common;
    using Data.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore.Internal;
    using Microsoft.Extensions.Logging;
    using Services.Interfaces;
    using ViewModels.Home;
    using ViewModels.Subject;

    public class SubjectsController : Controller
    {
        private readonly ILogger<SubjectsController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISubjectsService _subjectsService;
        private readonly ITeachersService _teachersService;
        private readonly IStudentsService _studentsService;
        private readonly IParentsService _parentsService;
        private readonly ISchoolsServices _schoolsServices;

        public SubjectsController(
            ILogger<SubjectsController> logger,
            UserManager<ApplicationUser> userManager,
            ISubjectsService subjectsService,
            ITeachersService teachersService,
            IStudentsService studentsService,
            IParentsService parentsService,
            ISchoolsServices schoolsServices)
        {
            _logger = logger;
            _userManager = userManager;
            _subjectsService = subjectsService;
            _teachersService = teachersService;
            _studentsService = studentsService;
            _parentsService = parentsService;
            _schoolsServices = schoolsServices;
        }

        public async Task<IActionResult> SubjectsList()
        {
            var viewModel = new SubjectsListViewModel();
            var subjects = await GetSubjectsBasedOnUserRoleAsync();
            if (subjects == null)
            {
                return RedirectToAction("Error", "Home");
            }

            viewModel.Subjects = subjects;

            return View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var viewModel = _subjectsService.GetById<SubjectViewModel>(id);
            return View(viewModel);
        }

        private async Task<IEnumerable<SubjectViewModel>> GetSubjectsBasedOnUserRoleAsync()
        {
            if (User.IsInRole(GlobalConstants.TeacherRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var teacherId = _teachersService.GetIdByUniqueId(user.UniqueGradebookId);
                if (teacherId == null)
                {
                    return null; // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _subjectsService.GetAllByTeacherId<SubjectViewModel>(teacherId.Value);
            }

            if (User.IsInRole(GlobalConstants.StudentRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var studentId = _studentsService.GetIdByUniqueId(user.UniqueGradebookId);
                if (studentId == null)
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _subjectsService.GetAllByStudentId<SubjectViewModel>(studentId.Value);
            }

            if (User.IsInRole(GlobalConstants.ParentRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var studentIds = _parentsService.GetStudentIdsByParentUniqueId(user.UniqueGradebookId);
                if (!studentIds.Any())
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _subjectsService.GetAllByMultipleStudentIds<SubjectViewModel>(studentIds);
            }

            if (User.IsInRole(GlobalConstants.PrincipalRoleName))
            {
                var user = await _userManager.GetUserAsync(User);
                var schoolIds = _schoolsServices.GetAllByUserId<SchoolViewModel>(user.UniqueGradebookId).Select(s => s.Id);
                if (!schoolIds.Any())
                {
                    return null;  // RedirectToAction("Error", "Home"); // Maybe add reasonable message?
                }

                return _subjectsService.GetAllBySchoolId<SubjectViewModel>(schoolIds.FirstOrDefault());
            }

            return _subjectsService.GetAll<SubjectViewModel>();
        }
    }
}

Web/Gradebook.Web/Areas/Principal/Views/Management/CreateClass.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.ClassCreateInputModel
@{
    ViewData["Title"] = "Add Class";
}

<h3 class="page-heading">Add new class</h3>
<form asp-action="CreateClass" method="post">
    <div>
        <label asp-for="Class.Letter">Class letter</label>
        <input asp-for="Class.Letter" class="form-control"/>
        <span asp-validation-for="Class.Letter" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Class.Year">The year which the class will be: </label>
        <input asp-for="Class.Year" class="form-control"  aria-describedby="yearGradeHelpBlock"/>
        <span asp-validation-for="Class.Year" class="text-danger"></span>
        <small id="yearGradeHelpBlock" class="form-text text-muted">
            Ex: If you type the number 3, the class will be at 3rd grade
        </small>
    </div>
    
    <div>
        <label asp-for="Class.YearCreated">Which year has the class been registered: </label>
        <input asp-for="Class.YearCreated" class="form-control" aria-describedby="schoolYearHelpBlock"/>
        <span asp-validation-for="Class.YearCreated" class="text-danger"></span>
        <small id="schoolYearHelpBlock" class="form-text text-muted">
            Ex: 2012
        </small>
    </div>
    
    <div>
        <label asp-for="Class.TeacherId"></label>
        <select asp-for="Class.TeacherId" 
                class="form-control" 
                asp-items="Model.Teachers">
            <option>Select teacher from list: </option>
        </select>
        <span asp-validation-for="Class.TeacherId" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Create Class"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/CreateParent.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.ParentCreateInputModel
@{
    ViewData["Title"] = "Add parent";
}

<h3 class="page-heading">Add new parent</h3>
<form asp-action="CreateParent" method="post">
    <div>
        <label asp-for="Parent.FirstName">Parent's first name</label>
        <input asp-for="Parent.FirstName" class="form-control"/>
        <span asp-validation-for="Parent.FirstName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Parent.LastName">Parent's last name</label>
        <input asp-for="Parent.LastName" class="form-control"/>
        <span asp-validation-for="Parent.LastName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Parent.PhoneNumber"></label>
        <input asp-for="Parent.PhoneNumber" class="form-control"/>
        <span asp-validation-for="Parent.PhoneNumber" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Parent.StudentIds"></label>
        <select asp-for="Parent.StudentIds" 
                class="form-control" 
                asp-items="Model.Students" multiple>
            <option>Select students from list: </option>
        </select>
        <span asp-validation-for="Parent.StudentIds" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Create Parent"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/CreateStudent.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.StudentCreateInputModel
@{
    ViewData["Title"] = "Add student";
}

<h3 class="page-heading">Add new student</h3>
<form asp-action="CreateStudent" method="post">
    <div>
        <label asp-for="Student.FirstName">Student's first name</label>
        <input asp-for="Student.FirstName" class="form-control"/>
        <span asp-validation-for="Student.FirstName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.LastName">Student's last name</label>
        <input asp-for="Student.LastName" class="form-control"/>
        <span asp-validation-for="Student.LastName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.BirthDate"></label>
        <input asp-for="Student.BirthDate" class="form-control" type="date"/>
        <span asp-validation-for="Student.BirthDate" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.PersonalIdentificationNumber"></label>
        <input asp-for="Student.PersonalIdentificationNumber" class="form-control"/>
        <span asp-validation-for="Student.PersonalIdentificationNumber" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.SchoolId"></label>
        <select asp-for="Student.SchoolId" 
                class="form-control" 
                asp-items="Model.Schools">
            <option>Select school from list: </option>
        </select>
        <span asp-validation-for="Student.SchoolId" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.ClassId"></label>
        <select asp-for="Student.ClassId" 
                class="form-control" 
                asp-items="Model.Classes">
            <option>Select class from list (double check school is same as class): </option>
        </select>
        <span asp-validation-for="Student.ClassId" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Create Student"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/CreateSubject.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.SubjectCreateInputModel
@{
    ViewData["Title"] = "Add Subject";
}

<h3 class="page-heading">Add new subject</h3>
<form asp-action="CreateSubject" method="post">
    <div>
        <label asp-for="Subject.Name">Subject's name</label>
        <input asp-for="Subject.Name" class="form-control"/>
        <span asp-validation-for="Subject.Name" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Subject.YearGrade">Grade that is to have this subject: </label>
        <input asp-for="Subject.YearGrade" class="form-control"  aria-describedby="yearGradeHelpBlock"/>
        <span asp-validation-for="Subject.YearGrade" class="text-danger"></span>
        <small id="yearGradeHelpBlock" class="form-text text-muted">
            Ex: If you type the number 3, the subject will be available for students at 3rd grade
        </small>
    </div>
    
    <div>
        <label asp-for="Subject.SchoolYear">School year: </label>
        <input asp-for="Subject.SchoolYear" class="form-control" aria-describedby="schoolYearHelpBlock"/>
        <span asp-validation-for="Subject.SchoolYear" class="text-danger"></span>
        <small id="schoolYearHelpBlock" class="form-text text-muted">
            Ex: 2020-2021
        </small>
    </div>
    
    <div>
        <label asp-for="Subject.TeacherId"></label>
        <select asp-for="Subject.TeacherId" 
                class="form-control" 
                asp-items="Model.Teachers">
            <option>Select teacher from list: </option>
        </select>
        <span asp-validation-for="Subject.TeacherId" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Create Subject"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/CreateTeacher.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.TeacherCreateInputModel
@{
    ViewData["Title"] = "Add teacher";
}

<h3 class="page-heading">Add new teacher</h3>
<form asp-action="CreateTeacher" method="post">
    <div>
        <label asp-for="Teacher.FirstName">Teacher's first name</label>
        <input asp-for="Teacher.FirstName" class="form-control"/>
        <span asp-validation-for="Teacher.FirstName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Teacher.LastName">Teacher's last name</label>
        <input asp-for="Teacher.LastName" class="form-control"/>
        <span asp-validation-for="Teacher.LastName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Teacher.SchoolId"></label>
        <select asp-for="Teacher.SchoolId" 
                class="form-control" 
                asp-items="Model.Schools">
            <option>Select school from list: </option>
        </select>
        <span asp-validation-for="Teacher.SchoolId" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" class="btn btn-primary create-record-btn" value="Create Teacher"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/DeleteClass.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.ClassModifyInputModel
@{
    ViewData["Title"] = "Delete class";
}

<h3 class="page-heading">Delete class</h3>
<form asp-action="DeleteClass" method="post">
    <div>
            <label asp-for="Class.Letter">Class letter</label>
            <input asp-for="Class.Letter" class="form-control" readonly/>
            <span asp-validation-for="Class.Letter" class="text-danger"></span>
        </div>
        
        <div>
            <label asp-for="Class.Year">The year which the class will be: </label>
            <input asp-for="Class.Year" class="form-control"  aria-describedby="yearGradeHelpBlock" readonly/>
            <span asp-validation-for="Class.Year" class="text-danger"></span>
            <small id="yearGradeHelpBlock" class="form-text text-muted">
                Ex: If you type the number 3, the class will be at 3rd grade
            </small>
        </div>
        
        <div>
            <label asp-for="Class.YearCreated">Which year has the class been registered: </label>
            <input asp-for="Class.YearCreated" class="form-control" aria-describedby="schoolYearHelpBlock" readonly/>
            <span asp-validation-for="Class.YearCreated" class="text-danger"></span>
            <small id="schoolYearHelpBlock" class="form-text text-muted">
                Note: If empty, current year would be used
            </small>
        </div>
    
    <div>
        <label asp-for="Class.TeacherId">Teacher: </label>
        <input asp-for="Class.TeacherId" class="form-control" aria-describedby="schoolYearHelpBlock" readonly/>
        <span asp-validation-for="Class.TeacherId" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" name="onSubmitAction" class="btn btn-light" value="Cancel"/>
        <input type="submit" name="onSubmitAction" class="btn btn-primary delete-record-btn" value="Delete Class" onclick="return confirm(`Are you sure you want to delete that class?`)"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/DeleteParent.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.ParentModifyInputModel
@{
    ViewData["Title"] = "Delete parent";
}

<h3 class="page-heading">Delete parent</h3>
<form asp-action="DeleteParent" method="post">
    <div>
            <label asp-for="Parent.FirstName">Parent's first name</label>
            <input asp-for="Parent.FirstName" class="form-control" readonly/>
            <span asp-validation-for="Parent.FirstName" class="text-danger"></span>
        </div>
        
        <div>
            <label asp-for="Parent.LastName">Parent's last name</label>
            <input asp-for="Parent.LastName" class="form-control" readonly/>
            <span asp-validation-for="Parent.LastName" class="text-danger"></span>
        </div>
        
        <div>
            <label asp-for="Parent.PhoneNumber"></label>
            <input asp-for="Parent.PhoneNumber" class="form-control" readonly/>
            <span asp-validation-for="Parent.PhoneNumber" class="text-danger"></span>
        </div>

    <hr/>
    <div class="center-group">
        <input type="submit" name="onSubmitAction" class="btn btn-light" value="Cancel"/>
        <input type="submit" name="onSubmitAction" class="btn btn-primary delete-record-btn" value="Delete Parent" onclick="return confirm(`Are you sure you want to delete that parent?`)"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/DeleteStudent.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.StudentModifyInputModel
@{
    ViewData["Title"] = "Delete student";
}

<h3 class="page-heading">Delete student</h3>
<form asp-action="DeleteStudent" method="post">
    <div>
        <label asp-for="Student.FirstName">Student's first name</label>
        <input asp-for="Student.FirstName" class="form-control" readonly/>
        <span asp-validation-for="Student.FirstName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.LastName">Student's last name</label>
        <input asp-for="Student.LastName" class="form-control" readonly/>
        <span asp-validation-for="Student.LastName" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.BirthDate"></label>
        <input asp-for="Student.BirthDate" class="form-control" type="date" readonly/>
        <span asp-validation-for="Student.BirthDate" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Student.PersonalIdentificationNumber"></label>
        <input asp-for="Student.PersonalIdentificationNumber" class="form-control" readonly/>
        <span asp-validation-for="Student.PersonalIdentificationNumber" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" name="onSubmitAction" class="btn btn-light" value="Cancel"/>
        <input type="submit" name="onSubmitAction" class="btn btn-primary delete-record-btn" value="Delete Student" onclick="return confirm(`Are you sure you want to delete that student?`)"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/DeleteSubject.cshtml
@model Gradebook.Web.Areas.Principal.ViewModels.InputModels.SubjectModifyInputModel
@{
    ViewData["Title"] = "Delete subject";
}

<h3 class="page-heading">Delete subject</h3>
<form asp-action="DeleteSubject" method="post">
    <div>
        <label asp-for="Subject.Name">Subject's name</label>
        <input asp-for="Subject.Name" class="form-control" readonly/>
        <span asp-validation-for="Subject.Name" class="text-danger"></span>
    </div>
    
    <div>
        <label asp-for="Subject.YearGrade">Grade that is to have this subject: </label>
        <input asp-for="Subject.YearGrade" class="form-control"  aria-describedby="yearGradeHelpBlock" readonly/>
        <span asp-validation-for="Subject.YearGrade" class="text-danger"></span>
        <small id="yearGradeHelpBlock" class="form-text text-muted">
            Ex: If you type the number 3, the subject will be available for students at 3rd grade
        </small>
    </div>
    
    <div>
        <label asp-for="Subject.SchoolYear">School year: </label>
        <input asp-for="Subject.SchoolYear" class="form-control" aria-describedby="schoolYearHelpBlock" readonly/>
        <span asp-validation-for="Subject.SchoolYear" class="text-danger"></span>
        <small id="schoolYearHelpBlock" class="form-text text-muted">
            Ex: 2020-2021
        </small>
    </div>
    
    <div>
        <label asp-for="Subject.TeacherId">Teacher: </label>
        <input asp-for="Subject.TeacherId" class="form-control" aria-describedby="schoolYearHelpBlock" readonly/>
        <span asp-validation-for="Subject.TeacherId" class="text-danger"></span>
    </div>

    <hr/>
    <div class="center-group">
        <input type="submit" name="onSubmitAction" class="btn btn-light" value="Cancel"/>
        <input type="submit" name="onSubmitAction" class="btn btn-primary delete-record-btn" value="Delete Subject" onclick="return confirm(`Are you sure you want to delete that subject?`)"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Gradebook.Web/Areas/Principal/Views/Management/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1>Hello, @User.Identity.Name!</h1>
    <h2>This is a management page for people in principle role. You can do some adjustments here. For example: </h2>

    <button type="button" class="btn btn-outline-success">
        <a class="page-link-with-hover" asp-action="CreateStudent" title="Add student">
            Add new student 
        </a>
    </button>
    <button type="button" class="btn btn-outline-success">
        <a class="page-link-with-hover" asp-action="CreateParent" title="Add parent">
            Add new parent 
        </a>
    </button>
    <button type="button" class="btn btn-outline-success">
        <a class="page-link-with-hover" asp-action="CreateTeacher" title="Add teacher">
            Add new teacher 
        </a>
    </button>
    <button type="button" class="btn btn-outline-success">
        <a class="page-link-with-hover" asp-action="CreateSubject" title="Add subject">
            Add new subject 
        </a>
    </button>
    <button type="button" class="btn btn-outline-success">
        <a class="page-link-with-hover" asp-action="CreateClass" title="Add class">
            Add new class 
        </a>
    </button>
    <hr>
    <button type="button" class="btn btn-outline-success">
        <a class="page-link-with-hover" asp-action="AddClassToSubject" title="Add class">
            Assign class to subject 
        </a>
    </button>
    <hr>
    <button type="button" class="btn btn-light">
        <a class="page-link-with-hover" asp-area="" asp-controller="Subjects" asp-action="SubjectsList" title="List of subjects">
            Go to subjects list 
        </a>
    </button>
    <button type="button" class="btn btn-light">
        <a class="page-link-with-hover" asp-area="" asp-controller="Classes" asp-action="ClassesList" title="List of classes">
            Go to classes list 
        </a>
    </button>
</div>